name: Build dependent natives

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          mingw-w64 \
          autoconf automake libtool

    # =========================
    # Build plutosvg (CMake)
    # =========================
    - name: Build plutosvg
      shell: bash
      run: |
        mkdir -p build/plutosvg
        cd build/plutosvg

        if [ "${{ matrix.os }}" = "windows" ]; then
          cmake ../../include/plutosvg \
            -DCMAKE_SYSTEM_NAME=Windows \
            -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
            -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
            -DBUILD_SHARED_LIBS=OFF \
            -DPLUTOSVG_BUILD_STATIC=ON
        else
          cmake ../../include/plutosvg \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DPLUTOSVG_BUILD_STATIC=ON
        fi

        make -j

    # =========================
    # Build FreeType
    # =========================
    - name: Build FreeType
      shell: bash
      run: |
        cd include/freetype

        if [ "${{ matrix.os }}" = "windows" ]; then
          ./autogen.sh || true
          ./configure \
          --host=x86_64-w64-mingw32 \
          --enable-static --disable-shared \
          --without-zlib --without-png --without-bzip2 --without-harfbuzz \
          CFLAGS="-O2 -DPLATFORM_MINGW -D_POSIX_C_SOURCE=200809L"
        else
          ./autogen.sh || true
          ./configure \
            CFLAGS="-fPIC" --enable-static --disable-shared \
            --without-png --without-bzip2 --without-harfbuzz
        fi

        make -j

    # =========================
    # Collect artifacts
    # =========================
    - name: Collect artifacts
      shell: bash
      run: |
        mkdir -p build/artifacts

        if [ "${{ matrix.os }}" = "windows" ]; then
          cp build/plutosvg/*.a build/artifacts/plutosvg-windows.a || true
          cp include/freetype/objs/.libs/libfreetype.a build/artifacts/freetype-windows.a || true
        else
          cp build/plutosvg/*.a build/artifacts/plutosvg-linux.a || true
          cp include/freetype/objs/.libs/libfreetype.a build/artifacts/freetype-linux.a || true
        fi


    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dependency-build-${{ matrix.os }}-${{ github.run_number }}
        path: |
          build/*

    # # =========================
    # # Commit artifacts
    # # =========================
    # - name: Commit artifacts
    #   run: |
    #     git config user.name "github-actions"
    #     git config user.email "github-actions@github.com"

    #     git add build/artifacts

    #     git commit -m "Update native libs (${{ matrix.os }})" || echo "No changes"

    #     git push
